# Generated by Django 5.1.7 on 2025-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librery_app', '0004_alter_autor_biografia_alter_editorial_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, db_column='T001Biografia', null=True),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='telefono',
            field=models.CharField(blank=True, db_column='T002Telefono', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_final',
            field=models.DateField(blank=True, db_column='T005FechaDEvolucion', null=True),
        ),
    ]
