# Generated by Django 5.1.7 on 2025-03-09 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id_miembro', models.AutoField(db_column='T004IdMiembro', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T004Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='T004Apellido', max_length=100)),
                ('email', models.CharField(db_column='T001Biografia', max_length=100, unique=True)),
                ('fecha_membresia', models.DateField(db_column='T004Membresia')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'T004Miembro',
            },
        ),
        migrations.AlterField(
            model_name='editorial',
            name='telefono',
            field=models.CharField(db_column='T002Telefono', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='T003IdLibro', editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='T003Titulo', max_length=100)),
                ('resumen', models.TextField(db_column='T003Resumen')),
                ('isbn', models.CharField(db_column='T003ISBN', max_length=100)),
                ('publicacion', models.DateField(db_column='T003AñoPublicacion')),
                ('autor', models.ForeignKey(db_column='T003IdAutor', on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='librery_app.autor')),
                ('editorial', models.ForeignKey(db_column='T003IdEditorial', on_delete=django.db.models.deletion.CASCADE, related_name='editorial', to='librery_app.editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'T003Libro',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(db_column='T005Prestamo', editable=False, primary_key=True, serialize=False)),
                ('fecha_inicial', models.DateField(db_column='T005FechaPrestamo')),
                ('fecha_final', models.DateField(db_column='T005FechaDEvolucion')),
                ('libro', models.ForeignKey(db_column='T005Libro', on_delete=django.db.models.deletion.CASCADE, related_name='prestamo', to='librery_app.libro')),
                ('miembro', models.ForeignKey(db_column='T005Miembro', on_delete=django.db.models.deletion.CASCADE, related_name='miembro', to='librery_app.miembro')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'db_table': 'T005Prestamo',
            },
        ),
    ]
