# Generated by Django 5.1.7 on 2025-03-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librery_app', '0002_miembro_alter_editorial_telefono_libro_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='email',
            field=models.CharField(db_column='T004Biografia', max_length=100, unique=True),
        ),
    ]
