# Generated by Django 5.1.7 on 2025-03-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librery_app', '0003_alter_miembro_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, db_column='T001Biografia'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='telefono',
            field=models.CharField(blank=True, db_column='T002Telefono', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_final',
            field=models.DateField(blank=True, db_column='T005FechaDEvolucion'),
        ),
    ]
